services:
  web:
    build: .
    command: python -u main.py
    ports:
      - 5000:5000
    volumes:
      - .:/raviflix-main
    links:
      - db
  db:
    image: mongo:latest
    hostname: localhost
    ports:
      - 27017:27017









# services:
#   web:
#     build: .
#     command: python -u main.py
#     #ports:
#     #  - "80:80"
#     volumes:
#       - .:/app
#     links:
#       - db
# db:
#   image: mongo:latest
#     hostname: 'localhost'
#     # environment:
#     #   - MONGO_INITDB_DATABASE=animal_db
#     #   - MONGO_INITDB_ROOT_USERNAME=root
#     #   - MONGO_INITDB_ROOT_PASSWORD=pass
#     # volumes:
#     #   - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
#     ports:
#       - 27017:27017
